baseURL = "http://example.org/"
disqusShortname = ""
languageCode = "en-us"
title = "Forty"
theme = "forty33"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
custom_css = []
custom_js = []
description = "Your description"
favicon = "favicon.ico"
image = ""
name = "Your name"
[params.banner]
buttontext = "Get Started"
subtitle = "A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP\nAND RELEASED UNDER THE CREATIVE COMMONS."
title = "Hi, my name is Forty"
[params.contact]
buttonclear = "Clear"
buttonsend = "Send message"
enable = true
[[params.contact.address]]
city = "City, ST 00000"
country = "Country"
street = "Street"
title = "Address"
[[params.contact.email]]
email = "example@domain.com"
title = "Email"
[[params.contact.phone]]
phone = "(000) 000-0000 x1234"
title = "Phone"
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [this page](/)"
[params.footer]
copyright = "Company Name"
enable = true
[[params.footer.quicklinks]]
alt = "HTML5 UP"
text = "Design: "
url = "https://www.html5up.net"
[[params.footer.social]]
icon = "fa-twitter"
label = "Twitter"
url = "https://www.twitter.com"
[[params.footer.social]]
icon = "fa-facebook"
label = "Facebook"
url = "https://www.facebook.com"
[[params.footer.social]]
icon = "fa-instagram"
label = "Instagram"
url = "https://www.instagram.com"
[[params.footer.social]]
icon = "fa-github"
label = "GitHub"
url = "https://www.github.com"
[[params.footer.social]]
icon = "fa-linkedin"
label = "LinkedIn"
url = "https://www.linkedin.com"
[params.navigation]
menu = "Menu"
subtitle = "By HTML5 Up"
title = "Forty"
[[params.navigation.button1]]
name = "Get Started"
url = "blogs"
[[params.navigation.button2]]
name = "Log In"
url = "#"
[[params.navigation.links]]
name = "Home"
url = "#"
[[params.navigation.links]]
name = "Blogs"
url = "blogs"
[[params.navigation.links]]
name = "Generic Blog"
url = "blogs/ipsum"
[[params.navigation.links]]
name = "Elements"
url = "elements.html"
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "pic01.jpg"
subtitle = "Ipsum Dolor Sit Amet"
title = "Aliquam"
url = "blogs/aliquam"
[[params.tiles.showcase]]
image = "pic02.jpg"
subtitle = "Feugiat Amet Tempus"
title = "Tempus"
url = "blogs/tempus"
[[params.tiles.showcase]]
image = "pic03.jpg"
subtitle = "Lorem Etiam Nullam"
title = "Magna"
url = "blogs/magna"
[[params.tiles.showcase]]
image = "pic04.jpg"
subtitle = "Nisl Sed Aliquam"
title = "Ipsum"
url = "blogs/ipsum"
[[params.tiles.showcase]]
image = "pic05.jpg"
subtitle = "Ipsum Dolor Sit Amet"
title = "Consequat"
url = "blogs/ipsum"
[[params.tiles.showcase]]
image = "pic06.jpg"
subtitle = "Feugiat Amet Tempus"
title = "Etiam"
url = "blogs/ipsum"
[params.two]
buttontext = "Get Started"
enable = true
subtitle = "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."
title = "Massa libero"
url = "blogs"
